name: GitHub Release

on:
    # Triggers the workflow on pushing a tag only
    push:
        tags: "*"
        branches:
            - "!*"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        steps:
            # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
            # GitHub Actions by default doesn't check out tags, so make sure those are included
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Set Variables
              run: |
                  echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
                  git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt

            - name: Download LazyLib
              uses: wei/wget@v1
              with:
                args: -O libs/LazyLib.zip https://github.com/LazyWizard/lazylib/releases/download/2.7b/LazyLib.2.7b.zip

            - name: Download MagicLib
              uses: wei/wget@v1
              with:
                args: -O libs/MagicLib.zip https://www.patreon.com/file?h=62002109&i=10010143

            - name: Extract Libs
              run: |
                cd libs
                7z x LazyLib.zip
                7z x MagicLib.zip
                ls -la

            - name: Build Mod Zipfile
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 7.5
                  arguments: build release

            - name: Publish Release on GitHub
              uses: "ncipollo/release-action@v1"
              with:
                  name: ${{ env.VERSION }}
                  tag: ${{ env.VERSION }}
                  bodyFile: changes.txt
                  draft: true
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "alkemia-armoury-*.zip"
